### ISSUE TITLE
How CPU speed was measured?

### ISSUE THREAD

**Issue by mrgloom** [agisoft-llc/cloud-scripts#1]
How CPU speed was measured? 

For example for p3.8xlarge x2.1 speedup is for (4xV100 + 32 vCPUs) vs (GTX1080 + i7 5960X) ? or (32 vCPUs) vs ( i7 5960X)? or (1 vCPUs) vs ( i7 5960X)?

**Comment by PolarNick239** [comment]
This is relative CPU speedup for p3.8xlarge over Baseline, so it is for (p3.8xlarge's CPU) vs (Baseline's CPU) - i.e. (32 vCPUs) vs (i7 5960X). Measured workload wasn't using GPU at all.

**Comment by mrgloom** [comment]
So it's literally just x2.1 speedup of 32 CPU server over top i7 CPU? looks weird. Is it because of  virtualization or is it something special about Photoscan?

**Comment by PolarNick239** [comment]
I don't know for sure, but it seems that aws vCPUs are hyperthreaded, so 32 vCPUs ~ 16 cores/32 threads, while 5960X is 8 cores/16 threads, so x2 speedup looks quite expected.

But there are also possible memory bandwidth differences (number of channels), possible overhead of multiple sockets and many other possible reasons.
