### ISSUE TITLE
Problem with grafics driver

### ISSUE THREAD

**Issue by freetec1** [agisoft-llc/cloud-scripts#11]
Hello,

i am experiencing some problems with (in my opinion) the drivers for the graphic card. Installing everything works fine and metashape detects the graphics card. But after some reboots somehow it can´t detect the graphics card anymore. I checked with the following command:
`sudo lshw -c video`
the output when everything is working:

```
*-display:0 UNCLAIMED
       description: VGA compatible controller
       product: Amazon.com, Inc.
       vendor: Amazon.com, Inc.
       physical id: 3
       bus info: pci@0000:00:03.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller
       configuration: latency=0
       resources: memory:fe000000-fe3fffff memory:c0000-dffff
  *-display:1
       description: Display controller
       product: Advanced Micro Devices, Inc. [AMD/ATI]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 1e
       bus info: pci@0000:00:1e.0
       logical name: /dev/fb0
       version: c3
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi msix bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 mode=4096x3112 visual=truecolor xres=4096 yres=3112
       resources: iomemory:100-ff iomemory:100-ff irq:0 memory:1040000000-104fffffff memory:1050000000-10501fffff memory:feb00000-feb7ffff
```

and when it is not working after some reboot (without changing anything):

```
*-display:0 UNCLAIMED

       description: VGA compatible controller
       product: Amazon.com, Inc.
       vendor: Amazon.com, Inc.
       physical id: 3
       bus info: pci@0000:00:03.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller
       configuration: latency=0
       resources: memory:fe000000-fe3fffff memory:c0000-dffff
  *-display:1 UNCLAIMED
       description: Display controller
       product: Advanced Micro Devices, Inc. [AMD/ATI]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 1e
       bus info: pci@0000:00:1e.0
       version: c3
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi msix cap_list
       configuration: latency=0
       resources: iomemory:100-ff iomemory:100-ff memory:1040000000-104fffffff memory:1050000000-10501fffff memory:feb00000-feb7ffff
```

working for me so far is to uninstall the drivers for the gpu and then run the cloudscript installation again. but this takes some time and is no great experience.

Does somebody else have this issue or is there some way to resolve this?

Kind regards

**Comment by PolarNick239** [comment]
Hi,

this is strange. Can you please check do you observe the same problem if you:
1) launch clean instance
2) configure it with scripts
3) reboot computer - check that lshw output is OK and 'clinfo' detects AMD GPU
4) reboot computer - check that lshw output is OK and 'clinfo' detects AMD GPU
5) reboot computer - ...
6) repeat until you will be sure that it is stable or until you will reproduce the problem

This test is supposed to check is the problem related to just rebooting, or is it related to GPU usage? Or you are already reporting the bug about problem after multiple rebooting without any other actions? If so - how many reboots it approximately takes?

Also, when you encounter this "UNCLAIMED GPU" problem - have you tried to just reboot computer? May be this is a rare bug in GPU initialization.
