### ISSUE TITLE
Question regarding ./photoscan.sh -r script -platform offscreen

### ISSUE THREAD

**Issue by mrgloom** [agisoft-llc/cloud-scripts#2]
As I can see here
https://agisoft.freshdesk.com/support/solutions/articles/31000133141-how-to-run-the-script-in-headless-mode-from-the-command-line
I can run Photoscan without X-server, like: `./photoscan.sh -r script -platform offscreen`

But I wonder do I steel need VirtualVNC, VirtualGL, etc. if I don't run Photoscan via GUI? Or maybe Photoscan still will be working but slower and I need some extra work? here I'm more talking about of using Photoscan with GPU, does it need something like 'hardware acceleration'?

**Comment by PolarNick239** [comment]
No, for headless computations (even with GPU usage via OpenCL/CUDA) you don't need to install virtualgl - you only need to install GPU drivers for CUDA/OpenCL. If you use NVidia GPUs - you can just check your drivers with executing nvidia-smi (it should list all GPUs).
