### ISSUE TITLE
What operation system did you use to test?

### ISSUE THREAD

**Issue by WadeWuu** [agisoft-llc/cloud-scripts#4]
I tried to use Ubuntu to test. However, when I installed the Nvidia driver, there was a loop in the Ubuntu login interface. I solved this problem by installing the  Nvidia driver without installing openGL. And I installed the Mesa to use openGL. However, the version of openGL is 3.0. I want to use the openGL 4.x. I do not know how to upgrade the version of openGL.
And one more question, how did you install the openGL? Did you install openGL while installing the Nvidia driver?

**Comment by PolarNick239** [comment]
This repository contains scripts to simplify the configuration process. You just need to follow [these steps](https://github.com/agisoft-llc/cloud-scripts#how-to-use).
