### ISSUE TITLE
WARNING: Could not find libjawt.so, JRELoadError (MacOS)

### ISSUE THREAD

**Issue by Murray2015** [agisoft-llc/cloud-scripts#9]
Hi :) 

I've tried following your guide up to the line 
`/opt/TurboVNC/bin/vncviewer ${ip}:5901`

Where I get the error 
`
WARNING: Could not find libjawt.so. Some features may not work properly.
/opt/TurboVNC/bin/vncviewer: 58: exec: java: not found
`

I tried installing java (`sudo apt update; sudo apt install default-jre; sudo apt install openjdk-11-jre-headless; sudo apt install openjdk-8-jre-headless; sudo apt install default-jdk`), but I don't use Java so have no idea what I'm doing! 

Am I doing something wrong? 

I'm using a p2.xlarge with the Ubuntu 18.04 sever AMI.

**Comment by PolarNick239** [comment]
Hi!

Note that vncviewer is launched on the client side. It seems that ```openjdk-8-jre-headless``` package installed on the client side should be enough.

What is the output of ```locate libjawt.so```? If it can't find something like ```/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so``` - try again after executing ```sudo updatedb```.

**Comment by Murray2015** [comment]
Hi @PolarNick239, thanks for the fast reply!

**Comment by Murray2015** [comment]
HI @PolarNick239, thanks for the fast reply! 

That was helpful, it wasn't clear to me that vncviewer was launched on the client side. That has gotten me further forward, but not joy yet: I'm now getting the error `JRELoadError` on the turbovncviewer window when I run `/opt/TurboVNC/bin/vncviewer my_instance_ip:5901` on the client side. 

I get no errors up to this point. I'm running MacOS 10.15.6 with zsh. I've opened all ports to incoming traffic on EC2, and tried a couple of java versions with home-brew. Have you got any ideas on how to debug?

**Comment by PolarNick239** [comment]
I don't know for sure (not using MacOS), but googling with ```mac turbovnc JRELoadError``` leads to these promising looking threads:

1) https://www.gitmemory.com/issue/TurboVNC/turbovnc/199/572397818

2) https://github.com/TurboVNC/turbovnc/issues/143

**Comment by PolarNick239** [comment]
Feel free to re-open if the problem persists.
